var hachi = [
    {
        name: "Hachi Sitting",
        month: 11,
        date: 20,
        year: 2020,
        url: "Hachi/Hachi (1).jpg",
    },
    {
        name: "Hachi Sitting",
        month: 11,
        date: 20,
        year: 2020,
        url: "Hachi/Hachi (2).jpg",
    },
    {
        name: "Hachi Sitting",
        month: 11,
        date: 20,
        year: 2020,
        url: "Hachi/Hachi (3).jpg",
    },
    {
        name: "Hachi Sitting",
        month: 11,
        date: 20,
        year: 2020,
        url: "Hachi/Hachi (4).jpg",
    },
    {
        name: "Hachi Sitting",
        month: 6,
        date: 26,
        year: 2019,
        url: "Hachi/Hachi (5).jpg",
    },
    {
        name: "Hachi Sitting",
        month: 6,
        date: 26,
        year: 2019,
        url: "Hachi/Hachi (6).jpg",
    },
    {
        name: "Hachi in Bed",
        month: 12,
        date: 21,
        year: 2019,
        url: "Hachi/Hachi (7).jpg",
    },
    {
        name: "Hachi in Bed",
        month: 12,
        date: 21,
        year: 2019,
        url: "Hachi/Hachi (8).jpg",
    },
    {
        name: "Hachi in Bed",
        month: 12,
        date: 21,
        year: 2019,
        url: "Hachi/Hachi (9).jpg",
    },
    {
        name: "Hachi in Bed",
        month: 12,
        date: 21,
        year: 2019,
        url: "Hachi/Hachi (10).jpg",
    },
    {
        name: "Hachi in Bed",
        month: 12,
        date: 21,
        year: 2019,
        url: "Hachi/Hachi (11).jpg",
    },
    {
        name: "Hachi in Bed",
        month: 12,
        date: 21,
        year: 2019,
        url: "Hachi/Hachi (12).jpg",
    },
    {
        name: "Hachi in Bed",
        month: 4,
        date: 16,
        year: 2020,
        url: "Hachi/Hachi (13).jpg",
    },
    {
        name: "Hachi in Bed",
        month: 4,
        date: 16,
        year: 2020,
        url: "Hachi/Hachi (14).jpg",
    },
    {
        name: "Hachi on Shoes",
        month: 4,
        date: 22,
        year: 2020,
        url: "Hachi/Hachi (15).jpg",
    },
    {
        name: "Hachi in Bed",
        month: 2,
        date: 18,
        year: 2019,
        url: "Hachi/Hachi (16).jpg",
    },
    {
        name: "Hachi Sleeping",
        month: 8,
        date: 15,
        year: 2020,
        url: "Hachi/Hachi (17).jpg",
    },
    {
        name: "Hachi Sleeping",
        month: 10,
        date: 24,
        year: 2020,
        url: "Hachi/Hachi (18).jpg",
    },
    {
        name: "Hachi Sleeping",
        month: 10,
        date: 24,
        year: 2020,
        url: "Hachi/Hachi (19).jpg",
    },
    {
        name: "Hachi Sleeping",
        month: 11,
        date: 11,
        year: 2020,
        url: "Hachi/Hachi (20).jpg",
    },
    {
        name: "Hachi + Pillow",
        month: 11,
        date: 11,
        year: 2020,
        url: "Hachi/Hachi (21).jpg",
    },
    {
        name: "Hachi Sleeping + Pillow",
        month: 11,
        date: 12,
        year: 2020,
        url: "Hachi/Hachi (22).jpg",
    },
    {
        name: "Hachi Sleeping",
        month: 11,
        date: 16,
        year: 2020,
        url: "Hachi/Hachi (23).jpg",
    },
    {
        name: "Hachi on His Walk",
        month: 2,
        date: 9,
        year: 2019,
        url: "Hachi/Hachi (24).jpg",
    },
    {
        name: "Hachi Eating",
        month: 6,
        date: 13,
        year: 2019,
        url: "Hachi/Hachi (25).jpg",
    },
    {
        name: "Hachi Eating",
        month: 6,
        date: 13,
        year: 2019,
        url: "Hachi/Hachi (25).jpg",
    },
    {
        name: "Hachi Waiting",
        month: 6,
        date: 18,
        year: 2019,
        url: "Hachi/Hachi (26).jpg",
    },
    {
        name: "Hachi Cleaning",
        month: 6,
        date: 28,
        year: 2019,
        url: "Hachi/Hachi (27).jpg",
    },
    {
        name: "Walking Hachi",
        month: 6,
        date: 29,
        year: 2019,
        url: "Hachi/Hachi (28).jpg",
    },
    {
        name: "Hachi Sitting",
        month: 11,
        date: 5,
        year: 2019,
        url: "Hachi/Hachi (29).jpg",
    },
    {
        name: "Hachi Laying Down",
        month: 11,
        date: 5,
        year: 2019,
        url: "Hachi/Hachi (30).jpg",
    },
    {
        name: "Confused Hachi",
        month: 11,
        date: 5,
        year: 2019,
        url: "Hachi/Hachi (31).jpg",
    },
    {
        name: "Hachi Hiding",
        month: 8,
        date: 14,
        year: 2018,
        url: "Hachi/Hachi (32).jpg",
    },
]




